### Site Settings ###
title               : Dev Haral
description         : >-
                      Hi there, I'm  Dev Haral - a third-year Mechanical Engineering B.Tech student at IIT Mandi, with a burning passion for the exciting and ever-evolving field of Deep Learning and Natural Language Processing. I believe that my background in Mechanical Engineering gives me a unique perspective and an interdisciplinary approach to problem-solving, which, when combined with my passion for Deep Learning and NLP, opens up a world of possibilities for me. I am excited to embark on this journey of growth and development, and I'm looking forward to the opportunities and challenges that lie ahead.
#baseurl             : "/portfolYOU"                     # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : YoussefRaafatNasry/portfolYOU     # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme        : YoussefRaafatNasry/portfolYOU
open_new_tab        : false                             # Opens external URLs in new tab (works for posts, projects and navbar only)


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - docs/pages/tags.html
  - docs/pages/404.html
  - docs/pages/index.md
#- documentation/partials/**                           # For Documentation Only


### Author Info ###
author:
  name              : Dev Haral
  image             : assets/dev.jpg
  behance           : your_username
# dribbble          : your_username
  email             : devharal777@gmail.com
  facebook          : your_username
  github            : Devharal
# gitlab            : your_username
# instagram         : your_username
# kaggle            : your_username
  linkedin          : dev-haral-007786220
  medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
  twitter           : your_username
# vimeo             : your_username
# youtube           : your_channel_name
# keybase           : your_username


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name
  # elements:                                             # For Documentation Only
  #   output: true                                        # For Documentation Only


### Disqus ###
disqus:
  shortname: your-short-name-disqus                     # Your website Shortname on disqus


### Analytics ###
analytics:
  enabled: false                                        # Set true to enable analytics
  google:
    tracking_id: your-google-tracking-id


### Buy me a coffee ###
# See https://www.buymeacoffee.com/
buymeacoffee:
  enabled: false
  username: your_username
  color: "#007bff"
  message: "Thank you for visiting."                    # Message to be displayed aside from the button for a few seconds.
  description: "Support me on Buy me a coffee!"


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  # - scope:                                              # For Documentation Only
  #     path: ""                                          # For Documentation Only
  #     type: "elements"                                  # For Documentation Only
  #   values:                                             # For Documentation Only
  #     layout: "element"                                 # For Documentation Only
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false                                   # Set to true to enable disqus comments


### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
